version: "3"
services:
  dev:
    build:
      context: ./docker
    tty: true
    working_dir: /work
    volumes:
      - $PWD:/work
  fixed:
    build:
      context: ./docker
      dockerfile: Dockerfile.fixed
    tty: true
    working_dir: /work
    volumes:
      - $PWD:/work
